#!/usr/bin/env bash
# displays Best School 10 times but for the 9th iteration, displays Best School and then Hi
for i in 0 1 2 3 4 5 6 7 8 9
do
    if [ "$i" -eq 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
done
