#!/usr/bin/env bash
# displays Best School 10 times but for the 9th iteration, displays Best School and then Hi
x=0
while [ $x -le 9 ]
do
    if [ "$x" -eq 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    x=$(( x + 1 ))
done
